//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_EF_Kimbilir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Detail
    {
        public int PersonID { get; set; }
        public short Age { get; set; }
        public string Adress { get; set; }
        public string GithubProfile { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
